# Generated by Django 4.2.6 on 2023-11-02 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250, verbose_name="Название")),
                ("description", models.TextField(verbose_name="Описание")),
                ("slug", models.SlugField(unique=True, verbose_name="Символьный код")),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250, verbose_name="Название")),
                ("description", models.TextField(verbose_name="Описание")),
                ("slug", models.SlugField(unique=True, verbose_name="Символьный код")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Цена",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Количество на складе"
                    ),
                ),
                (
                    "availability",
                    models.BooleanField(default=True, verbose_name="Доступность"),
                ),
                (
                    "number_of_views",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Кол-во просмотров"
                    ),
                ),
                (
                    "number_of_sales",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Кол-во покупок"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category",
                        to="catalog.category",
                        verbose_name="Категория товара",
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
                "ordering": ["-id"],
            },
        ),
    ]
