# Generated by Django 4.2.6 on 2023-11-02 21:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_alter_item_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="image",
            field=models.URLField(default=1, verbose_name="Адрес изображения"),
            preserve_default=False,
        ),
    ]
