# Generated by Django 4.2.6 on 2023-11-03 20:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0004_color_item_colors"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="collection",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SM", "Лето"),
                    ("WN", "Зима"),
                    ("AU", "Осень"),
                    ("SP", "Весна"),
                ],
                default="WN",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="material",
            field=models.CharField(
                blank=True,
                choices=[
                    ("LN", "Лен"),
                    ("CT", "Хлопок"),
                    ("WL", "Шерсть"),
                    ("SL", "Шелк"),
                ],
                default="SL",
                max_length=200,
            ),
        ),
    ]
