# Generated by Django 4.2.6 on 2023-11-05 08:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0005_item_collection_item_material"),
    ]

    operations = [
        migrations.CreateModel(
            name="Galery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("img", models.URLField(verbose_name="Адрес изображения")),
            ],
        ),
        migrations.AlterField(
            model_name="item",
            name="collection",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SM", "Лето"),
                    ("WN", "Зима"),
                    ("AU", "Осень"),
                    ("SP", "Весна"),
                ],
                default="WN",
                max_length=200,
                verbose_name="Коллекция",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="material",
            field=models.CharField(
                blank=True,
                choices=[
                    ("LN", "Лен"),
                    ("CT", "Хлопок"),
                    ("WL", "Шерсть"),
                    ("SL", "Шелк"),
                ],
                default="SL",
                max_length=200,
                verbose_name="Материал",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="images",
            field=models.ManyToManyField(
                blank=True, to="catalog.galery", verbose_name="Галерея"
            ),
        ),
    ]
