# Generated by Django 4.2.6 on 2023-11-01 05:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(default="-------", max_length=100)),
                ("password", models.CharField(default="1111", max_length=20)),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="телефон"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="электронная почта"
                    ),
                ),
                (
                    "discount",
                    models.PositiveIntegerField(
                        default=0, verbose_name="накопительная скидка"
                    ),
                ),
                (
                    "amount_of_purchases",
                    models.PositiveIntegerField(
                        default=0, verbose_name="общая сумма покупок"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="профиль",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
